channels:
- anaconda
- conda-forge
- pytorch
dependencies:
- python=3.8.16
- pip:
  - mlflow==2.4
  - azureml-train-automl-runtime==1.51.0.post2
  - inference-schema
  - azureml-interpret==1.51.0
  - azureml-defaults==1.51.0
  - pytorch-transformers==1.0.0
  - spacy==2.1.8
  - https://aka.ms/automl-resources/packages/en_core_web_sm-2.1.0.tar.gz
- numpy==1.22.3
- pandas==1.1.5
- scikit-learn==0.22.1
- py-xgboost==1.3.3
- fbprophet==0.7.1
- holidays==0.10.3
- psutil==5.9.5
- pytorch==1.11.0
- cudatoolkit==9.0
name: project_environment
